// flow-typed signature: ca890d4e52454c08406ca317978da033
// flow-typed version: <<STUB>>/parse-diff_v^0.4.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'parse-diff'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'parse-diff' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'parse-diff/index' {
  declare module.exports: $Exports<'parse-diff'>;
}
declare module 'parse-diff/index.js' {
  declare module.exports: $Exports<'parse-diff'>;
}
