// flow-typed signature: b5cf21b9705d62e659e681881ca72ac7
// flow-typed version: <<STUB>>/timing-safe-equal_v^1.0.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'timing-safe-equal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'timing-safe-equal' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'timing-safe-equal/browser' {
  declare module.exports: any;
}

declare module 'timing-safe-equal/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'timing-safe-equal/browser.js' {
  declare module.exports: $Exports<'timing-safe-equal/browser'>;
}
declare module 'timing-safe-equal/index' {
  declare module.exports: $Exports<'timing-safe-equal'>;
}
declare module 'timing-safe-equal/index.js' {
  declare module.exports: $Exports<'timing-safe-equal'>;
}
declare module 'timing-safe-equal/test.js' {
  declare module.exports: $Exports<'timing-safe-equal/test'>;
}
